### ISSUE TITLE
Budget Line search view

### ISSUE THREAD

**Issue by andhit-r** [open-synergy/account-budgeting#1]
Tidak ada filter yang dapat digunakan pada menu **Accounting -> Reporting -> Generic Reporting -> Budget -> Budget Line**. Menyulitkan user dalam melihat data. Usulan filter untuk budget line:
1. Dapat dicari berdasarkan:
   
   1.1 Budget
   1.2 Budgetary Position
   1.3 Start Date
   1.4 End Date
2. Dapat dikelompokan berdasarkan:
   
   2.1. Budget
   2.2. Start Date
   2.3. Analytic Account
   2.4. Budgetary Position

**Comment by andhit-r** [comment]
Bagaimana pendapat @azmimr67 ?

**Comment by azmimr67** [comment]
Setuju Mas.
